---
- name: Converge
  hosts: all
  vars:
    generic_packages:
      - gcc
      - git
    pacman_packages:
      - gcc-d
    deb_packages:
      - g++
    rpm_packages:
      - gcc-c++
  tasks:
    - name: "Include os-packages"
      include_role:
        name: "ansible-role-os-packages"
