---
dependency:
  name: galaxy
driver:
  name: docker
lint: yamllint .
platforms:
  - name: debian
    image: debian:latest
  - name: ubuntu-lts
    image: ubuntu:latest
  - name: fedora
    image: fedora:latest
  - name: opensuse-tumbleweed
    image: opensuse/tumbleweed:latest
  - name: opensuse-leap
    image: opensuse/leap:latest
  - name: archlinux
    image: archlinux:latest
provisioner:
  name: ansible
verifier:
  name: ansible
