---
- name: Verify
  hosts: all
  tasks:
    - name: Check for tools
      ansible.builtin.command: "gcc --version"
      register: "gcc_cmd"

    - name: Check if installed
      ansible.builtin.assert:
        that: "gcc_cmd.rc == 0"

    - name: Check for tools
      ansible.builtin.command: "g++ --version"
      register: "gpp_cmd"

    - name: Check if installed
      ansible.builtin.assert:
        that: "gpp_cmd.rc == 0"

    - name: Check for tools
      ansible.builtin.command: "git --version"
      register: "git_cmd"

    - name: Check if installed
      ansible.builtin.assert:
        that: "git_cmd.rc == 0"

    - name: Check for gcc-d on Arch
      when: ansible_facts["pkg_mgr"]  == "pacman"
      block:
        - name: Check gdc version
          ansible.builtin.command: "gdc --version"
          register: cmd
        - name: gcc-d is installed
          ansible.builtin.assert:
            that: cmd.rc == 0
